### ISSUE TITLE
Problème de tri avec le Drag and Drop

### ISSUE THREAD

**Issue by Lulu-rep** [Lulu-rep/Pokedaine_Angular_Project#2]
Lors du chargement initial de la page et lors de l'ajout des taches, les taches se mettent dans la catégorie Undifined tout en gardant le statut qu'il devrait normalement avoir (celui choisi lors de la création de la taches).

**Comment by Pierre-Gei** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Drag and drop](https://trello.com/c/p856KCkX/6-drag-and-drop)
